student_id        = "stagiaire07"
resource_suffix   = "jnb"
aws_region        = "eu-west-1"
availability_zone = "eu-west-1a"
ami_id            = "ami-08c7a4b4f234dfa77"
instance_type     = "t3.micro"
key_pair_name     = ""
